package org.siyapath.client;

/**
 * Created by IntelliJ IDEA.
 * User: HP
 * Date: 7/10/12
 * Time: 4:48 AM
 * To change this template use File | Settings | File Templates.
 */
public class JobStatusUI extends javax.swing.JFrame{

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

    UserHandler handler;

    /** Creates new form JobStatusUI */
    public JobStatusUI(UserHandler handler) {
        initComponents();
        this.handler = handler;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jobIDLabel = new javax.swing.JLabel();
        jobIDTextField = new javax.swing.JTextField();
        jobStatusLabel = new javax.swing.JLabel();
        viewStatisButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaskTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jobIDLabel.setText("Enter Job ID:");

        jobIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobIDTextFieldActionPerformed(evt);
            }
        });

        jobStatusLabel.setText("Job is ");

        viewStatisButton.setText("View Status");
        viewStatisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStatisButtonActionPerformed(evt);
            }
        });

        TaskTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null},
                        {null, null},
                        {null, null}
                },
                new String[]{
                        "Task", "Status"
                }
        ));
        jScrollPane1.setViewportView(TaskTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jobStatusLabel)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jobIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(27, 27, 27)
                                                                .addComponent(jobIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(53, 53, 53)
                                                                .addComponent(viewStatisButton))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(73, 73, 73)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jobIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jobIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewStatisButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jobStatusLabel)
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>

    private void viewStatisButtonActionPerformed(java.awt.event.ActionEvent evt) {
        handler.demo();






        // TODO add your handling code here:
    }

    private void jobIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JobStatusUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify
    private javax.swing.JTable TaskTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jobIDLabel;
    private javax.swing.JTextField jobIDTextField;
    private javax.swing.JLabel jobStatusLabel;
    private javax.swing.JButton viewStatisButton;
    // End of variables declaration

}