/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.siyapath.service;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Data exchanged during gossip communication between two nodes
 */
public class GossipData implements org.apache.thrift.TBase<GossipData, GossipData._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GossipData");

  private static final org.apache.thrift.protocol.TField GOSSIP_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("gossipData", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new GossipDataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new GossipDataTupleSchemeFactory());
  }

  public Map<String,NodeData> gossipData; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    GOSSIP_DATA((short)1, "gossipData");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // GOSSIP_DATA
          return GOSSIP_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.GOSSIP_DATA, new org.apache.thrift.meta_data.FieldMetaData("gossipData", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, NodeData.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GossipData.class, metaDataMap);
  }

  public GossipData() {
  }

  public GossipData(
    Map<String,NodeData> gossipData)
  {
    this();
    this.gossipData = gossipData;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GossipData(GossipData other) {
    if (other.isSetGossipData()) {
      Map<String,NodeData> __this__gossipData = new HashMap<String,NodeData>();
      for (Map.Entry<String, NodeData> other_element : other.gossipData.entrySet()) {

        String other_element_key = other_element.getKey();
        NodeData other_element_value = other_element.getValue();

        String __this__gossipData_copy_key = other_element_key;

        NodeData __this__gossipData_copy_value = new NodeData(other_element_value);

        __this__gossipData.put(__this__gossipData_copy_key, __this__gossipData_copy_value);
      }
      this.gossipData = __this__gossipData;
    }
  }

  public GossipData deepCopy() {
    return new GossipData(this);
  }

  @Override
  public void clear() {
    this.gossipData = null;
  }

  public int getGossipDataSize() {
    return (this.gossipData == null) ? 0 : this.gossipData.size();
  }

  public void putToGossipData(String key, NodeData val) {
    if (this.gossipData == null) {
      this.gossipData = new HashMap<String,NodeData>();
    }
    this.gossipData.put(key, val);
  }

  public Map<String,NodeData> getGossipData() {
    return this.gossipData;
  }

  public GossipData setGossipData(Map<String,NodeData> gossipData) {
    this.gossipData = gossipData;
    return this;
  }

  public void unsetGossipData() {
    this.gossipData = null;
  }

  /** Returns true if field gossipData is set (has been assigned a value) and false otherwise */
  public boolean isSetGossipData() {
    return this.gossipData != null;
  }

  public void setGossipDataIsSet(boolean value) {
    if (!value) {
      this.gossipData = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case GOSSIP_DATA:
      if (value == null) {
        unsetGossipData();
      } else {
        setGossipData((Map<String,NodeData>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case GOSSIP_DATA:
      return getGossipData();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case GOSSIP_DATA:
      return isSetGossipData();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof GossipData)
      return this.equals((GossipData)that);
    return false;
  }

  public boolean equals(GossipData that) {
    if (that == null)
      return false;

    boolean this_present_gossipData = true && this.isSetGossipData();
    boolean that_present_gossipData = true && that.isSetGossipData();
    if (this_present_gossipData || that_present_gossipData) {
      if (!(this_present_gossipData && that_present_gossipData))
        return false;
      if (!this.gossipData.equals(that.gossipData))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(GossipData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    GossipData typedOther = (GossipData)other;

    lastComparison = Boolean.valueOf(isSetGossipData()).compareTo(typedOther.isSetGossipData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGossipData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gossipData, typedOther.gossipData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("GossipData(");
    boolean first = true;

    sb.append("gossipData:");
    if (this.gossipData == null) {
      sb.append("null");
    } else {
      sb.append(this.gossipData);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GossipDataStandardSchemeFactory implements SchemeFactory {
    public GossipDataStandardScheme getScheme() {
      return new GossipDataStandardScheme();
    }
  }

  private static class GossipDataStandardScheme extends StandardScheme<GossipData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, GossipData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // GOSSIP_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map10 = iprot.readMapBegin();
                struct.gossipData = new HashMap<String,NodeData>(2*_map10.size);
                for (int _i11 = 0; _i11 < _map10.size; ++_i11)
                {
                  String _key12; // required
                  NodeData _val13; // required
                  _key12 = iprot.readString();
                  _val13 = new NodeData();
                  _val13.read(iprot);
                  struct.gossipData.put(_key12, _val13);
                }
                iprot.readMapEnd();
              }
              struct.setGossipDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, GossipData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.gossipData != null) {
        oprot.writeFieldBegin(GOSSIP_DATA_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, struct.gossipData.size()));
          for (Map.Entry<String, NodeData> _iter14 : struct.gossipData.entrySet())
          {
            oprot.writeString(_iter14.getKey());
            _iter14.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GossipDataTupleSchemeFactory implements SchemeFactory {
    public GossipDataTupleScheme getScheme() {
      return new GossipDataTupleScheme();
    }
  }

  private static class GossipDataTupleScheme extends TupleScheme<GossipData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GossipData struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetGossipData()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetGossipData()) {
        {
          oprot.writeI32(struct.gossipData.size());
          for (Map.Entry<String, NodeData> _iter15 : struct.gossipData.entrySet())
          {
            oprot.writeString(_iter15.getKey());
            _iter15.getValue().write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GossipData struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map16 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.gossipData = new HashMap<String,NodeData>(2*_map16.size);
          for (int _i17 = 0; _i17 < _map16.size; ++_i17)
          {
            String _key18; // required
            NodeData _val19; // required
            _key18 = iprot.readString();
            _val19 = new NodeData();
            _val19.read(iprot);
            struct.gossipData.put(_key18, _val19);
          }
        }
        struct.setGossipDataIsSet(true);
      }
    }
  }

}

